# When merged to main, publish to npm by changesets
name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/setup-node@v2
        with:
          node-version: 16
      - run: pnpm install
      - run: pnpm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
